//swagger.ts
import Router from 'koa-router';
import path from 'path';
import swaggerJSDoc from 'swagger-jsdoc';  //import swagger-jsdoc

const swaggerRouter = new Router();

swaggerRouter.prefix('/swagger')   //set the router prefix
const swaggerDefinition = {
    info: {
        title: 'Forum API',        //doc title
        version: 'v1',             //doc version
        host: 'localhost: ' + process.env.PORT,    //doc address
        basePath: '/'              //base path,you could change if you want.
    }
}
const options = {
    swaggerDefinition,
    //includes all files needed to generate doc
    apis: [
        process.env.NODE_ENV == "production" ? path.join(__dirname,'./forum.js') : path.join(__dirname,'./forum.ts'),
        // path.join(__dirname, "./xxx.js"),
        // path.join(__dirname, "./xxx1.js"),
    ]
}
const swaggerSpec = swaggerJSDoc(options)

console.log(process.env.PORT)

// specification file generated by routers
swaggerRouter.get('/swagger.json', async function (ctx) {
    ctx.set('Content-Type', 'application/json')
    ctx.body = swaggerSpec
})
module.exports = swaggerRouter
